[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Apply Splash logic to Tsaunami Deck/Sleeve
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''local splashed = SMODS.always_scores(G.play.cards[i]) or next(find_joker('Splash'))'''
position = "at"
payload = '''
local splashed = SMODS.always_scores(G.play.cards[i]) or next(find_joker('Splash')) or G.GAME.selected_back.effect.center.key == "b_skh_tsaunami"
if CardSleeves then splashed = SMODS.always_scores(G.play.cards[i]) or next(find_joker('Splash')) or G.GAME.selected_back.effect.center.key == "b_skh_tsaunami" or G.GAME.selected_sleeve == "sleeve_skh_tsaunami" end
'''
match_indent = true

# Apply Serpent logic (but 5 cards) to Kind Worm and Omnipotent Worm (rolling on Kind Worm) Deck
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''if G.GAME.blind.name == 'The Serpent' and'''
position = "before"
payload = '''
if (G.GAME.selected_back.effect.center.key == "b_skh_kindworm" or
    (G.GAME.selected_back.effect.center.key == "b_skh_omnipotentworm" and
    G.GAME.selected_back.effect.center.config.extra.current_deck == "b_skh_kindworm")) and
    G.GAME.facing_blind and
    (G.GAME.current_round.hands_played > 0 or
    G.GAME.current_round.discards_used > 0) then
        hand_space = math.min(#G.deck.cards, 5)
end
'''
match_indent = true

# Apply Patient, Virgin, Chaos and Omnipotent loc handling when exiting to Menu
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''G.FUNCS.go_to_menu = function(e)'''
position = "after"
payload = '''
  if G.GAME.selected_back.effect.center.key == "b_skh_patientworm" or
    G.GAME.selected_back.effect.center.key == "b_skh_virginworm" or
    G.GAME.selected_back.effect.center.key == "b_skh_wormychaos" or
    G.GAME.selected_back.effect.center.key == "b_skh_omnipotentworm" then
      G.GAME.selected_back.effect.center.config.extra.in_game = false
  end
'''
match_indent = true